using Pkg
Pkg.add("DataFrames")
Pkg.add("Plots")
Pkg.add("StatsPlots")
Pkg.add("StatsBase")
Pkg.add("Statistics")
Pkg.add("TimeSeries")
Pkg.add("TSAnomalies")
Pkg.add("Forecast")
Pkg.add("MLJBase")
Pkg.add("StatsModels")
Pkg.add("GLM")
Pkg.add("ARIMA")
Pkg.add("Seasonal")
Pkg.add("PyCall")
Pkg.add("DataFramesMeta")
Pkg.add("Flux")
Pkg.add("Convex")
Pkg.add("ECOS")
Pkg.add("DelimitedFiles")
Pkg.add("MessyTimeSeries")
Pkg.add("TSML")

# Pkg.add("JuliaDB")